/*
 * Copyright 2025 The https://github.com/agent-sandbox/agent-sandbox Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package sandbox

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"sync"

	"github.com/agent-sandbox/agent-sandbox/pkg/activator"
	"k8s.io/klog/v2"
)

type ClientSessionCache struct {
	// TODO session cleanup?
	sessions sync.Map
}

type Handler struct {
	rootCtx      context.Context
	controller   *Controller
	sessionCache *ClientSessionCache
	activator    *activator.Activator
}

func NewHandler(rootCtx context.Context, c *Controller, a *activator.Activator) *Handler {
	cache := &ClientSessionCache{
		//sessions: make(map[string]*mcp.ClientSession),
	}

	return &Handler{
		rootCtx:      rootCtx,
		controller:   c,
		activator:    a,
		sessionCache: cache,
	}
}

func (a *Handler) CreateSandbox(r *http.Request) (interface{}, error) {
	user := "default-user" // TODO get user from auth

	var sb = GetDefaultSandbox()
	sb.User = user

	err := json.NewDecoder(r.Body).Decode(sb)
	if err != nil {
		return "", fmt.Errorf("failed to decode request body: %v", err)
	}

	// check sandbox with the same name already exists
	// if sb.Name is empty, it will be generated by controller, so no need to check
	if sb.Name != "" {
		exist, _ := a.controller.Get(sb.Name)
		if exist != nil {
			return "", fmt.Errorf("sandbox %s already exists", sb.Name)
		}
	}

	// init name and valid fields
	if err := sb.Make(); err != nil {
		return nil, fmt.Errorf("error create sandbox: %v", err)
	}

	klog.V(2).Infof("Create sandbox opts %v", sb)

	sbCreated, err := a.controller.Create(sb)

	if err != nil {
		klog.Errorf("Failed to create sandbox, err: %v", err)
		return "", fmt.Errorf("failed to create new sandbox, error: %v", err)
	}

	return sbCreated, nil
}

func (a *Handler) ListSandbox(r *http.Request) (interface{}, error) {
	//user := "default-user" // TODO get user from auth

	sbs, err := a.controller.ListAll()
	if err != nil {
		return "", fmt.Errorf("no sandboxes found %v", err)
	}

	return sbs, nil
}

func (a *Handler) GetSandbox(r *http.Request) (interface{}, error) {
	name := r.PathValue("name")
	if name == "" {
		return nil, fmt.Errorf("sandbox name is required")
	}

	klog.V(2).Infof("Get sandbox name=%s", name)

	sb, _ := a.controller.Get(name)
	if sb == nil {
		return "", fmt.Errorf("sandbox %s not found", name)
	}

	return sb, nil
}

func (a *Handler) DelSandbox(r *http.Request) (interface{}, error) {
	name := r.PathValue("name")
	if name == "" {
		return nil, fmt.Errorf("sandbox name is required")
	}

	klog.V(2).Infof("Delete sandbox name=%s", name)

	err := a.controller.Delete(name)
	if err != nil {
		return "", fmt.Errorf("failed to delete sandbox %s: %v", name, err)
	}

	return fmt.Sprintf("Sandbox %s deleted successfully", name), nil
}
