apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{.Sandbox.Name}}
  namespace: {{.Namespace}}
  annotations:
    sandbox-data:  |
      {{.RawData}}
  labels:
    owner: agent-sandbox
    sandbox: {{.Sandbox.Name}}
    sbx-id: {{.Sandbox.ID}}
    sbx-user: {{.Sandbox.User}}
    sbx-template: {{.Sandbox.Template}}
    sbx-pool: {{.Sandbox.IsPool}}
spec:
  replicas: 1
  selector:
    matchLabels:
      sandbox: {{.Sandbox.Name}}
  template:
    metadata:
      labels:
        owner: agent-sandbox
        sandbox: {{.Sandbox.Name}}
        sbx-id: {{.Sandbox.ID}}
        sbx-user: {{.Sandbox.User}}
        sbx-template: {{.Sandbox.Template}}
        sbx-pool: {{.Sandbox.IsPool}}
    spec:
{{ if index .Sandbox.Metadata "runtimeClassName" }}
      runtimeClassName: {{.Sandbox.Metadata.runtimeClassName}}
{{ end }}
      containers:
        - name: sandbox
          image: {{.Sandbox.Image}}
          imagePullPolicy: IfNotPresent
  {{if .Sandbox.Cmd}}
          command: [{{.Sandbox.Cmd}}]
  {{end}}
  {{if .Sandbox.Args}}
          args:
      {{range .Sandbox.Args }}
            - {{ . }}
      {{end }}
  {{end}}
          ports:
            - containerPort: {{.Sandbox.Port}}
          env:
            - name: INSTANCE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
  {{if .Sandbox.EnvVars}}
      {{range $name, $value := .Sandbox.EnvVars }}
            - name: {{$name}}
              value: {{printf "%q" $value}}
      {{end }}
  {{end}}
          resources:
            requests:
              cpu: {{.Sandbox.CPU}}
              memory: {{.Sandbox.Memory}}
            limits:
              cpu: {{.Sandbox.CPULimit}}
              memory: {{.Sandbox.MemoryLimit}}
  {{if not .Sandbox.TemplateObj.NoStartupProbe}}
          startupProbe:
            failureThreshold: 600
            tcpSocket:
              port: {{.Sandbox.Port}}
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 3
  {{end}}